version: "2"

services:
  spark:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./jars:/opt/jars
    ports:
      - "8080:8080"
      - "7077:7077"
  spark-worker-1:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  livy:
    image: apache-livy-docker
    container_name: livy
    environment:
      - SPARK_MASTER_ENDPOINT=spark
      - SPARK_MASTER_PORT=7077
      - LIVY_FILE_LOCAL_DIR_WHITELIST=/opt/
    ports:
      - "8998:8998"
    volumes:
      - $PWD/jars:/opt/jars
      - $PWD/livy.conf.extra:/opt/livy.conf.extra
    depends_on:
      - "spark"
      - "spark-worker-1"
